//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintJob.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int Id { get; set; }
        public string Worker { get; set; }
        public string MachineName { get; set; }
        public int Construction { get; set; }
        public int Element { get; set; }
        public System.DateTime PaintJobDate { get; set; }
        public int ColorCode { get; set; }
        public string Preparation { get; set; }
        public int CleanConstruction { get; set; }
        public int CleanElements { get; set; }
        public int ColorQuantity { get; set; }
        public int ThinnerQuantity { get; set; }
        public int HardenerQuantity { get; set; }
        public int MixQuantity { get; set; }
        public string PrefilterM3 { get; set; }
        public string FilterM3 { get; set; }
        public int AirPressure { get; set; }
        public string WaterInSystem { get; set; }
        public int GunColorPressure { get; set; }
        public int GunAirPressure { get; set; }
        public int GunAngle { get; set; }
        public int Temperature { get; set; }
        public string Wind { get; set; }
        public string OutsideJob { get; set; }
        public string Ratio { get; set; }
        public int WorkHours { get; set; }
        public int UsedMixQuantity { get; set; }
        public int WastedMixQuantity { get; set; }
        public int CleanGunQuantity { get; set; }
        public string GrainEffect { get; set; }
        public int ColorRepair { get; set; }
        public string Comment { get; set; }
    }
}
